name: CI

on: 
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
  
    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js
      uses: action/setup/node@v1
      with: 
        node-version: 12.x
    
    - name: Instalando dependências
      run: npm i
    
    - name: Testando com jest
      run: npm test --watchAll false