name: CI

on: 
  push:
    branches: [main]

env: 
  TESTE: ${{ secrets.TESTE }}

jobs:
  build:
    runs-on: ubuntu-latest
  
    steps:
    - uses: actions/checkout@v2
    
    - name: Instalando dependências
      run: npm i
    
    - name: Testando com jest
      run: npm test --watchAll false

    - name: teste
      run: echo "$TESTE"